### PR TITLE
35 rewrite logstream class

### LINKED ISSUE #35: Rewrite LogStream class to be unit testable
Right now, it is virtually impossible to tell anything about the internal processes within the LogStream class. 

Therefore, the unit tests aren't capable of detecting anything that could go right or wrong within the class.

Possible ideas:
* use virtual callbacks with a trivial default that should get invoked if the class logic is OK
* make the output stream configurable through inheritance, this could also be a nice way to make file logging easier to implement.
* add protected getters to the class members to monitor the goings-on.

... and test on a child class.

### PR DESCRIPTION
**Pull request by starturtle**
closes #35 

additional fixes were necessary from last rewrite.

### CODE REVIEW

File: utilities/logging.cpp [hunk 1]
```diff
@@ -118,11 +131,137 @@ TEST_CASE("Test is-active check")
...
+
+  logging::Level current() { return getLogLevel(); }
+  logging::Level minimum() { return getMinimumLogLevel(); }
+};
+
+template<typename T>
+void verify_log_by_type(StringLogStream& testStream, logging::Level logLevel, logging::Level minLevel, bool allowed, T inputOriginal, const std::string& expectedString)
+{
+  const std::string endString{ expectedString.empty() ? "" : expectedString + "\n" };
+  CHECK_EQ(minLevel, testStream.minimum());
```
Comment (starturtle) [inline utilities/logging.cpp:166]: would make for a nicer read with paragraph separation or section headers

**Review by starturtle — COMMENTED** [review]
near OK
